name: Install roxctl
description: Download roxctl for use in GitHub Actions
inputs:
  roxctl-release:
    description: "roxctl release version to be installed."
    required: false
    default: "latest"
  install-dir:
    description: "Where to install the roxctl binary."
    required: false
    default: "$HOME/.roxctl"
  central-endpoint:
    description: "ACS Central endpoint to download roxctl from. If not specified, roxctl will be downloaded from mirror.openshift.com."
    required: false
    default: ""
  central-token:
    description: "Token to access ACS Central endpoint."
    required: false
    default: ""
  skip-tls-verify:
    description: "Skip TLS certificate verification for Central's API endpoint."
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: Set up path on Linux/OSX
      if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      run: echo "${{ inputs.install-dir }}" >> $GITHUB_PATH
      shell: bash
    - name: Set up path on Windows
      shell: pwsh
      if: ${{ runner.os == 'Windows' }}
      run: echo "${{ inputs.install-dir }}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Download roxctl
      shell: bash
      run: |
        case "${{ runner.os }}" in
          macOS)   OS=darwin EXT='' ;;
          Windows) OS=windows EXT='.exe' ;;
          *)       OS=linux EXT='' ;;
        esac
        if [[ '${{ inputs.central-endpoint }}' == '' ]]; then
          ENDPOINT="https://mirror.openshift.com/pub/rhacs/assets/${{ inputs.roxctl-release }}/bin/${OS}/roxctl"
        else
          ENDPOINT="${{ inputs.central-endpoint}}/api/cli/download/roxctl-${OS}-amd64"
        fi

        # In case we get a central-endpoint and it didn't start with a scheme (e.g. when using the output
        # from central-login), add a HTTPS prefix.
        ENDPOINT="https://${ENDPOINT#https://}"

        SKIP_TLS_VERIFY=""
        if [[ '${{ inputs.skip-tls-verify }}' == "true" ]]; then
            SKIP_TLS_VERIFY="-k "
        fi
        mkdir -p ${{ inputs.install-dir }}
        curl -H "Authorization: Bearer ${{ inputs.central-token }}" -H "User-Agent: roxctl-installer-GHA" \
          ${SKIP_TLS_VERIFY}--fail -S -L --retry 5 --silent \
          "${ENDPOINT}${EXT}" --output "${{ inputs.install-dir }}/roxctl${EXT}"
        chmod +x "${{ inputs.install-dir }}/roxctl${EXT}"
        roxctl version
